name       : gst-plugins-bad
version    : 0.10.23
release    : 15
source     :
    - http://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-0.10.23.tar.xz : 03cf0786391c64625569072e904082a08861f05a63d64b2f8e8dad3f26d81bf9
license    :
    - GPL-2.0-or-alter
    - LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : Streaming media framework
description: |
    GStreamer is a streaming media framework that enables applications to share a common set of plugins for things like video encoding and decoding, audio encoding and decoding, audio and video filters, audio visualisation, web streaming and anything else that streams in real-time or otherwise. This package only provides base functionality and libraries.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(celt)
    - pkgconfig(dvdnav)
    - pkgconfig(gmodule-export-2.0)
    - pkgconfig(gstreamer-0.10)
    - pkgconfig(gstreamer-plugins-base-0.10)
    - pkgconfig(kate)
    - pkgconfig(libass)
    - pkgconfig(libcurl)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libexif)
    - pkgconfig(libmodplug)
    - pkgconfig(libpng)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(librtmp)
    - pkgconfig(neon)
    - pkgconfig(openal)
    - pkgconfig(opencv4)
    - pkgconfig(opus)
    - pkgconfig(sndfile)
    - pkgconfig(vdpau)
    - pkgconfig(vo-aacenc)
    - pkgconfig(x11)
    - bzip2-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-include-references.patch
    %configure --disable-apexsink --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/gstreamer-0.10/libgstnsf.so
